version: 2.1

orbs:
  docker: circleci/docker@2.1.3
  aws-ecr: circleci/aws-ecr@8.1.2

jobs:
  publish:
    parameters:
      image:
        type: string
      tag:
        type: string
        default: "${CIRCLE_SHA1}"
      registry:
        type: string
        default: docker.io
      aws-public-registry:
        type: boolean
        default: false
      aws-registry-id:
        type: env_var_name
        default: AWS_ECR_REGISTRY_ID
      aws-region:
        type: string
        default: "${AWS_REGION}"
    executor:
      name: docker/machine
      dlc: true
    steps:
      - checkout
      - aws-ecr/ecr-login:
          public-registry: << parameters.aws-public-registry >>
          registry-id: << parameters.aws-registry-id >>
          region: << parameters.aws-region >>
      - docker/build:
          image: << parameters.image >>
          tag: << parameters.tag >>
          registry: << parameters.registry >>
      - docker/push:
          image: << parameters.image >>
          tag: << parameters.tag >>
          registry: << parameters.registry >>

workflows:
  use-docker-orb:
    jobs:
      - publish:
          image: "kelvintaywl/fancy-nginx"
          tag: "orb-${CIRCLE_SHA1}"
          registry: "public.ecr.aws/z1j6a2i1"
          aws-public-registry: true
          aws-region: ap-northeast-1
