version: 2.1

commands:
  check-docker:
    steps:
      - run: docker version
      - run: docker info
      - run:
          name: check DOCKER_ env vars
          command: |
            # DOCKER_* env vars can be/are used to override some Docker config (e.g., for Docker + Remote Docker)
            # See https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
            (env | grep "DOCKER_") || true
      - run: docker image ls
      - run: docker ps -a

executors:
  ubuntu-2204-dlc:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true 
    resource_class: large

jobs:
  explore-docker-daemon-machine:
    executor: ubuntu-2204-dlc
    steps:
      - check-docker
      - checkout
      - run:
          name: Build image
          command: |
            docker image build --tag fancy-nginx .
      - run:
          name: Run & stop container
          command: |
            docker container run -P --name my-fancy-nginx --detach fancy-nginx 
            sleep 5
            docker ps
            docker container stop my-fancy-nginx
            docker ps -a
            docker image ls

workflows:
  explore-dlc-containers:
    jobs:
      - explore-docker-daemon-machine
