version: 2.1

executors:
  golang:
    # seen on passing (public) build
    # https://app.circleci.com/pipelines/github/prometheus/influxdb_exporter/240/workflows/d8ee81c4-a505-445f-9635-4679bfd8ad6a/jobs/647
    docker:
      - image: circleci/golang:latest

jobs:
  binfmt:
    parameters:
      exec:
        type: executor
        default: golang
      remote-docker-version:
        type: string
    executor: << parameters.exec >>
    steps:
      - setup_remote_docker:
          version: << parameters.remote-docker-version >>
      - run: docker version
      - run: |
          docker run --privileged linuxkit/binfmt:v0.8

workflows:
  main:
    jobs:
      - binfmt:
          matrix:
            parameters:
              remote-docker-version:
                - "19.03.8"
                - "20.10.18"
