version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywl

jobs:
  build_custom_nginx_machine:
    environment:
      <<: *environment
    machine:
      image: ubuntu-2204:2022.04.1
    parameters:
      image_name:
        type: string
        default: 'fancy-nginx'
      image_tag:
        type: string
        default: 'latest'
    steps:
      - checkout
      - run:
          name: Build image via Kaniko
          command: |
            ./config.sh
            ls -laH config.json

            # Kaniko cache is a GCP Cloud Build feature (uses GCR).
            # See https://cloud.google.com/build/docs/optimize-builds/kaniko-cache
            # Hence, this is not applicable when pushing to Docker Hub
            docker run \
                -v /home/circleci/project/config.json:/kaniko/.docker/config.json:ro \
                -v /home/circleci/project:/workspace \
                gcr.io/kaniko-project/executor:latest \
                --dockerfile /workspace/Dockerfile \
                --destination "${DOCKER_REGISTRY}/${DOCKER_USER}/<< parameters.image_name >>:kaniko-machine-${CIRCLE_SHA1}" \
                --context dir:///workspace/

workflows:
  # Builds a custom image,
  # spins it up for tests,
  # and publishes to Docker Hub!
  build_test_publish:
    jobs:
      - build_custom_nginx_machine:
          context: docker

