version: 2.1

jobs:
  remote-docker:
    parameters:
      docker-version:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - setup_remote_docker:
          # https://circleci.com/docs/building-docker-images/#docker-version
          version: << parameters.docker-version >>

workflows:
  main:
    jobs:
      - remote-docker:
          matrix:
            parameters:
              docker-version:
                - 20.10.18  # control; latest based on our docs
                - 20.10.19
                - 20.10.20
                - 20.10.21
                - 20.10.22
                - 20.10.23
