version: 2.1

defaults:
  environment: &environment
    DOCKER_REGISTRY: docker.io
    DOCKER_USER: kelvintaywl
    
orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

executors:
  ubuntu-2004-arm:
    # see https://circleci.com/docs/using-arm
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium

commands:
  check-docker:
    steps:
      - run: docker version
      - run: docker info
      - run:
          name: check DOCKER_ env vars
          command: |
            # DOCKER_* env vars can be/are used to override some Docker config (e.g., for Docker + Remote Docker)
            # See https://docs.docker.com/engine/reference/commandline/cli/#environment-variables
            (env | grep "DOCKER_") || true

jobs:
  aws-ecr-login:
    executor: ubuntu-2004-arm
    environment:
      <<: *environment
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - check-docker
      - aws-ecr/ecr-login

workflows:
  arm-aws-ecr:
    jobs:
      - aws-ecr-login
